spring:
  application:
    name: config-client


  config:
#    uri: http://localhost:8888
#    import: optional:configserver:http://localhost:8888/config-server
    import: configserver:http://user:123@localhost:8888
#    username: admin
#    password: admin123
#  cloud:





server:
  port: 7010